#!/bin/bash

cp -aRv /Volumes/software/Unrestricted/CoRD/ServerInstall/CoRD.app /Applications/

mkdir ~/Library/Application\ Support/CoRD
mkdir ~/Library/Application\ Support/CoRD/Servers

cp /Volumes/software/Unrestricted/CoRD/ServerInstall/PSA-Approval.rdp ~/Library/Application\ Support/CoRD/Servers/

open /Applications/CoRD.app

exit
